name: CI

on:
  pull_request:
    branches:
      - main

permissions:
    id-token: write
    contents: read

env:
  SRC_PROJECT_PATH: '/webapp01/webapp01.csproj' 
  AZURE_WEBAPP_PACKAGE_PATH: './src'            # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '9.0.x'                       # set this to the dot net version to use
  imageName: "webapp01"
  tag: ${{ github.sha }}

jobs:
  ci_build:
    name: Build Web App
    
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - uses: actions/checkout@main
      
      # Setup .NET Core SDK
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} 
      
      # Run dotnet build
      - name: dotnet build
        run: |
          dotnet restore ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}${{ env.SRC_PROJECT_PATH }}
          dotnet build --configuration Release ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}${{ env.SRC_PROJECT_PATH }}
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.imageName }}:${{ env.tag }}
